# Generated by Django 3.1.5 on 2021-02-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
